CS342/2023-Balance

.github/workflows/beta-deployment.yml
.github/workflows/build-and-test.yml
Balance.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Balance/BalanceAppDelegate.swift
Balance/BalanceAppTestingSetup.swift
Balance/Supporting Files/GoogleService-Info.plist
BalanceModules/Sources/BalanceOnboardingFlow/Consent.swift
README.md
fastlane/Fastfile

The PR https://github.com/CS342/2023-Balance/pull/17 removed a lot of the changes that happened in previous PRs. This PR adds the Firebase configuration back to the project.
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):

Re-add Files from #12 and #15

---

Balance.xcodeproj/project.pbxproj

*TestFlight is not working, possibly due to a build script issue*
*Pasted a new build script from Paul to hopefully remedy this.*
*Shouldn't break anything, still builds fine locally*
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):

Hopefully this build script change fixes the TestFlight issue.

---

Balance.xcodeproj/project.pbxproj
Balance/DistractionView.swift
Balance/WEB/GamesCellView.swift
Balance/WEB/GamesView.swift
Balance/WEB/GamesWebView.swift
Balance/WEB/SudokuWebView.swift

#52 Now you can select diferent games.  …

[BAL-52]-[GP]-Game List

---

Balance.xcodeproj/project.pbxproj
Balance.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Balance/DistractionView.swift
Balance/Gallery/VideoCollectionView.swift
Balance/Gallery/VideoGalleryView.swift

[BAL-73]-[GP]-Look Videos #73 
By …

[BAL-73]-[GP]-Look Videos

---

Balance.xcodeproj/project.pbxproj
Balance/Balance.swift
Balance/Chill/Meditation/MeditationView.swift
Balance/Chill/Timer/NewTimerView.swift
Balance/Diary/Store/NoteStore.swift
Balance/Diary/Views/DiaryHomeView.swift
Balance/Diary/Views/DiaryNoteEntryView.swift
Balance/Diary/Views/PastDiaryEntry.swift
Balance/Distraction/Drawing/DrawHomeView.swift
Balance/Distraction/Drawing/DrawView.swift
Balance/Distraction/Drawing/MandalaCollectionView.swift
Balance/Distraction/Drawing/PastDrawEntry.swift
Balance/Fealing/FacesScreenView.swift
Balance/Fealing/MoodEditorView.swift
Balance/Profile/PasswordUpdateView.swift
Balance/Profile/PersonalDataView.swift
Balance/Profile/ProfileView.swift

BAL-91-GP-Write how you feel

---

Balance.xcodeproj/project.pbxproj
Balance/Login/AuthViewModel.swift
Balance/Login/LoginView.swift
Balance/Login/OnboardingFlow.swift
Balance/Login/SignUpView.swift

BAL-2-GP-Login-Errors

---

Balance.xcodeproj/project.pbxproj
Balance/Diary/Views/DiaryHomeView.swift
Balance/Login/AuthViewModel.swift
Balance/Login/LoginView.swift
Balance/Profile/AvatarPreviewView.swift
Balance/Profile/PasswordUpdateView.swift
Balance/Utils/SearchBar.swift

BAL-20-GP-Password-Update renaming, added loading
BAL-7-GP-Signup loading
BAL-2-GP-Login loading
#21 
#2 Loading added
#7 Loading added
#20 Loading added
*Are there tests included? If yes, which situations …

BAL-21-GP-Password-RESET, added loading

---

Balance.xcodeproj/project.pbxproj
Balance/Distraction/Gallery/GalleryView.swift
Balance/Distraction/Gallery/ImageReviewRepository.swift
Balance/Distraction/Gallery/ImageView.swift

#44 Saving images votes on firestores by date/time
*Where should the reviewer start? Where is a good …

BAL-44-GP-Saving votes on firestore

---

Balance/Distraction/Music/iOS_SDK/SpotifyDataController.swift
Balance/Login/LoginViewLocal.swift

BAL-XX-GP-Swiftlint

---

Balance.xcodeproj/project.pbxproj
Balance/Distraction/Gallery/LookImages/CardImageView.swift
Balance/Distraction/Gallery/LookImages/GalleryView.swift
Balance/Distraction/Gallery/LookImages/ImageCollectionView.swift
Balance/Distraction/Gallery/LookImages/ImageView.swift
Balance/Distraction/Gallery/LookImages/Photo.swift
Balance/Distraction/Gallery/LookImages/PhotoArray.swift
Balance/Distraction/Gallery/LookImages/PhotoUploadView.swift
Balance/Profile/ProfileView.swift

BAL-43-GP-UploadImages

---

Balance/Chill/Meditation/MeditationSpotifyView.swift
Balance/Chill/Meditation/MeditationView.swift
Balance/Chill/Meditation/SleepView.swift
Balance/Chill/Meditation/YoutubeView.swift
Balance/Fealing/Mood/MoodEditorView.swift
Balance/NavBar/HeaderHome.swift
Balance/Profile/AvatarPreviewView.swift
Balance/Profile/ProfileView.swift
Balance/Utils/Constant.swift

BAL-35-GP-AvatarUpdate

---

Balance/Distraction/Drawing/DrawView.swift
Balance/Distraction/Gallery/LookImages/GalleryView.swift
Balance/Distraction/Gallery/LookImages/ImageCollectionView.swift
Balance/Distraction/Gallery/LookImages/ImageView.swift
Balance/Distraction/Music/iOS_SDK/SpotifyViewController.swift
Balance/Fealing/Guess/BoxView.swift
Balance/Fealing/Guess/GuessView.swift
Balance/Login/LoginViewLocal.swift
Balance/Utils/Constant.swift

BAL-141-GP-Improvements Phase1

---

Balance/Distraction/Games/GamesView.swift

BAL-146-GP-Sudoku-misspelled

---

Balance/Distraction/Gallery/LookImages/GalleryView.swift
Balance/Distraction/Gallery/LookImages/ImageView.swift

BAL-145-GP-Gallery image fix when removing photos

---

Balance/Distraction/DistractionView.swift
Balance/Distraction/Drawing/BackgroundDrawView.swift
Balance/Distraction/Drawing/ColoringHomeView.swift
Balance/Distraction/Drawing/Draw.swift
Balance/Distraction/Drawing/DrawHomeView.swift
Balance/Distraction/Drawing/DrawView.swift
Balance/Distraction/Drawing/PastEntryView.swift

BAL-149-GP-Drawing/Coloring Improvements

---

Balance/Distraction/Music/iOS_SDK/SpotifyView.swift
Balance/Distraction/Music/iOS_SDK/SpotifyViewController.swift
Balance/Profile/ProfileView.swift

BAL-XX-GP-Improvements Phase1

---

Balance.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Balance/Distraction/DistractionView.swift

BAL-153-GP-Title Correction

---

Balance.xcodeproj/project.pbxproj
Balance.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Balance/Distraction/Gallery/LookImages/ImageView.swift
Balance/Profile/EmailHelper.swift
Balance/Profile/ProfileView.swift
Balance/Supporting Files/Info.plist

BAL-155-GP-ShareFix

---

Balance/Balance.swift
Balance/Chill/ChillCellView.swift
Balance/Distraction/DistractionCellView.swift
Balance/Distraction/Drawing/DrawView.swift
Balance/Distraction/Drawing/Sketch/Classes/Main.storyboard
Balance/Distraction/Drawing/Sketch/Classes/SketchViewController.swift
Balance/Distraction/Games/GamesCellView.swift
Balance/Home/CellView.swift
Balance/Home/Home.swift
Balance/Home/NavigationView.swift
Balance/Profile/ProfileCellView.swift
Balance/Profile/ProfileView.swift
Balance/Utils/BalanceExtensions.swift
Balance/Utils/Constant.swift

BAL-183-GP-BPM-CONFIGURATION

---

.github/workflows/build-and-test.yml

- https://github.com/StanfordBDHG/.github/issues/65
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):

Fix CodeCov

---

Balance/Balance.swift

More info in #201 
In the context of renewing the TestFlight version (it expires every 90 days) we are creating this PR which should trigger the CI/CD pipeline and will publish to TF.
N/A
N/A
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):

(docs) - Adds TF date (BAL-201)
